name: ICTest Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:18-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
      - name: Check the next lint
        run: npm run lint
  audit:
    runs-on: ubuntu-latest
    container: node:18-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Audit The Dependencies
        run: npm audit
  type_check:
    runs-on: ubuntu-latest
    container: node:18-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
      - name: Check Type
        run: npx tsc --noEmit
  build:
    runs-on: ubuntu-latest
    container: node:18-alpine
    needs: [lint,audit,type_check]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
      - name: Check the next lint
        run: npm run build
  deploy: 
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: ictest-frontend
          envVariableKeys: NEXT_PUBLIC_API_URL
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.ICTEST_API_URL }}
          TARGET_NEXT_PUBLIC_API_URL: production
          TYPE_NEXT_PUBLIC_API_URL: plain 
      - name: deploy site to vercel      
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod' 